export const actionsTypes = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_COMPLETE_TODO: "TOGGLE_COMPLETE_TODO",
  TOGGLE_IS_EDITING: "TOGGLE_IS_EDITING",
  TOGGLE_IS_EDITING_COMPLETED: "TOGGLE_IS_EDITING_COMPLETED",
  EDIT_TODO: "EDIT_TODO",
};
